### ISSUE TITLE
Missing events for login/logoff

### ISSUE THREAD

**Issue by Danielss89** [ZF-Commons/ZfcUser#146]
@bjy EvanDotPro told me that you might have begun on this. Have you? Or can i do it?

**Comment by claytondaley** [comment]
I'm confused why this was closed.  Isn't this a critical, core feature so extensions can provide post-authentication behavior?  Alternatively, is the 'authenticate' event noted above the recommended solution?

**Comment by Danielss89** [comment]
yes, `authenticate` event is the same as login
