### ISSUE TITLE
UserController loginAction

### ISSUE THREAD

**Issue by j-r-t** [ZF-Commons/ZfcUser#195]
I noticed this in the loginAction

```
    if ($this->getOptions()->getUseRedirectParameterIfPresent() && $request->getQuery()->get('redirect')) {
        $redirect = $request->getQuery()->get('redirect');
    } else {
        $redirect = false;
    }
```

shouldn't it be

```
    if ($this->getOptions()->getUseRedirectParameterIfPresent() && $request->getPost()->get('redirect')) {
        $redirect = $request->getPost()->get('redirect');
    } else {
        $redirect = false;
    }
```

?. I was having problems with it continually returning false and then realised it should probably be getPost. The login form has a hidden redirect field..upon submit it passes this through post..not string (in regards to the view helper) 

eg. $this->ZfcUserLoginWidget(array('redirect'=>'foo');

creates
input type="hidden" name="redirect" value="foo" />

Thanks,

Jesse

**Comment by flod1** [comment]
have the same issue
