### ISSUE TITLE
question: how to overload UserController in another module?

### ISSUE THREAD

**Issue by xin-eatads** [ZF-Commons/ZfcUser#238]
Are the instructions in http://stackoverflow.com/questions/8783873/zf2-whats-the-best-practice-for-working-with-vendor-modules-form-classes still valid?

**Comment by thommykay** [comment]
@xin-eatads @EvanDotPro sadly controller overloading is not covered in Jurian's blog
experienced the following issue: 
http://stackoverflow.com/questions/32584950/extending-zfcusers-usercontroller-in-custom-module

Extending ZfcUser's original UserController throws the following:

Warning: Missing argument 1 for ZfcUser\Controller\UserController::__construct(), called in C:\xampp\htdocs\my-module\vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php on line 207 and defined in C:\xampp\htdocs\my-module\vendor\zf-commons\zfc-user\src\ZfcUser\Controller\UserController.php on line 66

InvalidArgumentException
C:\xampp\htdocs\hotel-portal2\vendor\zf-commons\zfc-user\src\ZfcUser\Controller\UserController.php:69
Message: You must supply a callable redirectCallback

**Comment by Danielss89** [comment]
It pretty much give you the error? You have to inject a callable into the controller...

**Comment by thommykay** [comment]
Overwriting only the `indexAction` and `registerAction` of ZfcUser's USerController for Customization

**Comment by Danielss89** [comment]
If it's layout only, you can just overwrite the view file, you don't need to overwrite the controller itself. If you want to overwrite other stuff, like form or something, don't extend the controller, just create a new one and overwrite the route.
