### ISSUE TITLE
ServiceNotFoundException on zfcuser_zend_db_adapter alias

### ISSUE THREAD

**Issue by ghost** [ZF-Commons/ZfcUser#244]
I installed and ran ZfcUser. The login page loads fine.  When I hit user/register I get the error: `Zend\ServiceManager\Exception\ServiceNotFoundException`

The message: `An alias "zfcuser_zend_db_adapter" was requested but no service could be found.` 

Pretty sure the problem is in module.config.php in:

``` php
'service_manager' => array(
        'aliases' => array(
            'zfcuser_zend_db_adapter' => 'Zend\Db\Adapter\Adapter',
        ),
    ),
```

Ive tried messing with the path to Db\Adapter but haven't found a solution.  Any help?

**Comment by navlan21** [comment]
Hi, i installed this today, and I initially got the error message, and the fix was in the local.php. 
following will define the missing service_manager, and fixes the error.
return array(
    'db' => array(
        'driver'    => 'PdoMysql',
        'hostname'  => 'localhost',
        'database'  => 'databasename',
        'username'  => 'user',
        'password'  => 'passwor',
    ),
    'service_manager' => array(
        'factories' => array(
            'Zend\Db\Adapter\Adapter' => 'Zend\Db\Adapter\AdapterServiceFactory',
        ),
    ),
);
