### ISSUE TITLE
Closed : Undefined table: 7 ERROR:  relation "user" does not exist Postgresql

### ISSUE THREAD

**Issue by ppantelakis** [ZF-Commons/ZfcUser#249]
When I try to register or work with database I get the error
SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "user" does not exist
LINE 1: SELECT "user".\* FROM "user" WHERE "email" = $1.

Because I use Postgresql and I don't want to create the table user into the default schema public but create  in other schema lets say "login" I changed the value 'table_name'=>'user', in file zfcuser.global to 'user'=>'table_name' => new TableIdentifier('user','login'),
Perhaps it help somebody.

**Comment by DidimoGabriel** [comment]
Good morning friends I am currently working on a project in laravel 5.3 with php and database in posgresql but I try to do a normal insert in my condominium table and I get the following error:
QueryException in Connection.php line 761:
SQLSTATE[42P01]: Undefined table: 7 ERROR: no existe la relación «condominia»
LINE 1: insert into "condominia" ("id", "id_mc", "domain", "name", "...
^ (SQL: insert into "condominia" ("id", "id_mc", "domain", "name", "country", "lang", "phone", "currency", "status", "updated_at", "created_at") values (3, 1.3, www.aph360, , Venezuela, Es, 04146399699, Bs, 100, 2016-11-21 13:08:15, 2016-11-21 13:08:15))

si alguien sabe algo al respecto sobre como solucionar tal error se agradece su participacion.muchas gracias

**Comment by Danielss89** [comment]
Please use english
