### ISSUE TITLE
question: session timeout

### ISSUE THREAD

**Issue by xin-eatads** [ZF-Commons/ZfcUser#274]
Is there a session timeout feature yet? Meaning, if a user login at 0900 and the session timeout is 30 mins, he gets auto logout at 0930.

Thanks!

**Comment by adamlundrigan** [comment]
I think this is more of a documentation issue than a bug.  There isn't currently a way to "automatically" set the session configuration from ZF2 app or module config ([reference](http://zend-framework-community.634137.n4.nabble.com/How-to-use-Zend-Session-Service-SessionConfigFactory-tp4660321p4660325.html)).  The closest you can get to that is:

1. Add [session factories and configuration](http://zf2.readthedocs.org/en/latest/modules/zend.session.config.html#service-manager-factory) to your application via a module config or `config/autoload` file:

    ```
    return [
        'service_manager' => [
            'factories' => [
                'Zend\Session\ManagerInterface' => 'Zend\Session\Service\SessionManagerFactory',
                'Zend\Session\Config\ConfigInterface' => 'Zend\Session\Service\SessionConfigFactory',
            ],
        ],
        'session_config' => [
            'cache_expire' => 900,
            'cookie_lifetime' => 900,
        ],
    ];
    ```

2. In `Module::onBootstrap`, pull an instance of the SessionManager.  This will inject the properly-configured SessionManager instance as the default for new session containers. 

    ```
    class Module
    {
        public function onBootstrap(MvcEvent $e)
        {
            $manager = $e->getApplication()->getServiceManager()->get('Zend\Session\ManagerInterface');
        }
    }
```

I've added this config to one of my ZfcUser-based apps and users are logged out after 15 minutes of inactivity.

**Comment by adamlundrigan** [comment]
I've added a [wiki page](https://github.com/ZF-Commons/ZfcUser/wiki/How-to-configure-a-session-timeout) with the above example.

@Danielss89 this is a ZF2 issue (lack of automatic configuration loading for SessionManager) so it can be closed here.
