### ISSUE TITLE
AdapterChain does not recognize a successful authentication

### ISSUE THREAD

**Issue by fabamb** [ZF-Commons/ZfcUser#321]
I'm trying to use two adapters in sequence to authenticate a user, the first that uses ldap and the second (the standard) that uses a db.

Because of the "bizarre" algorithm used to perform the authentication (instead of simply cycling on the adapter and check the result, it triggers an event and then uses the stored data in it) we have that the authentication performed by the second adapter overwrites the code and message returned by the first adapter even if it has successfully completed the authentication and the session has an identity.

This is because the check to see if a previous adapter was successful or not is performed by checking (in the head to the authenticate) if the parameter "is_satisfied" is present and "true" in storage (session).
Too bad that the storage of the two adapters have different namespaces and therefore do not share the same "space".

In fact, the method in the class AbstractAdapter getStorage is written like this:

```
public function getStorage()
{
    if (null === $this->storage) {
        $this->setStorage(new Storage\Session(get_called_class()));
    }

    return $this->storage;
}
```

Therefore, each has a different storage adapter if you do not add extra code, for example to set the same storage for all adapters before using them.

**Comment by nuxwin** [comment]
@Danielss89

Why this issue has been closed exactly?

Having possibility to have an authentication adapter chain would be great. For instance, you could have an authentication listener which composes one adapter chain and which trigger the authentication event. That authentication event would compose a request and response objects and also the authentication service. Thus, when then authentication event is triggered by the authentication listener, the adapter chain could invoke all authentication adapters and the first which would handle the authentication request could stop the process. To achieve this, the authentication adapter interface could provide a method which allow the authentication adapters to determine if they can handle the authentication request by checking the request object (isPost?, has expected header(s), has expected data...)... Also, each authentication adapter could use one or many credential resolver (dbTable resolver, Doctrine object repository resolver, Apache (htpasswd) resolver etc...).

The current implementation as I understand allows for multi-factor authentication. Well, in the current implementation, I think that one adapter could just short-circuit the authentication event, isn't it?
