### ISSUE TITLE
Weird Intermittent Error

### ISSUE THREAD

**Issue by bluebaroncompsci** [ZF-Commons/ZfcUser#341]
An error occurred
An error occurred during execution; please try again later.
Additional information:
Zend\Stdlib\Exception\InvalidArgumentException
File:
/vendor/zendframework/zendframework/library/Zend/Stdlib/ArrayObject/PhpReferenceCompatibility.php:189
Message:
Passed variable is not an array or object, using empty array instead
Stack trace:
#0 /vendor/zendframework/zendframework/library/Zend/Stdlib/ArrayObject/PhpReferenceCompatibility.php(414): Zend\Stdlib\ArrayObject\PhpReferenceCompatibility->exchangeArray(NULL)
#1 [internal function]: Zend\Stdlib\ArrayObject\PhpReferenceCompatibility->unserialize('a:4:{s:7:"stora...')
#2 /vendor/zendframework/zendframework/library/Zend/Session/SessionManager.php(95): session_start()
#3 /vendor/zendframework/zendframework/library/Zend/Session/AbstractContainer.php(78): Zend\Session\SessionManager->start()
#4 /vendor/zendframework/zendframework/library/Zend/Authentication/Storage/Session.php(63): Zend\Session\AbstractContainer->__construct('Zend_Auth', NULL)
#5 /vendor/zf-commons/zfc-user/src/ZfcUser/Authentication/Storage/Db.php(106): Zend\Authentication\Storage\Session->__construct()
#6 /vendor/zf-commons/zfc-user/src/ZfcUser/Authentication/Storage/Db.php(41): ZfcUser\Authentication\Storage\Db->getStorage()
#7 /vendor/zendframework/zendframework/library/Zend/Authentication/AuthenticationService.php(134): ZfcUser\Authentication\Storage\Db->isEmpty()
#8 /vendor/zf-commons/zfc-user/src/ZfcUser/View/Helper/ZfcUserIdentity.php(23): Zend\Authentication\AuthenticationService->hasIdentity()
#9 [internal function]: ZfcUser\View\Helper\ZfcUserIdentity->__invoke()
#10 /vendor/zendframework/zendframework/library/Zend/View/Renderer/PhpRenderer.php(400): call_user_func_array(Object(ZfcUser\View\Helper\ZfcUserIdentity), Array)
#11 /module/Application/view/layout/layout.phtml(97): Zend\View\Renderer\PhpRenderer->__call('zfcUserIdentity', Array)
#12 /module/Application/view/layout/layout.phtml(97): Zend\View\Renderer\PhpRenderer->zfcUserIdentity()
#13 /vendor/zendframework/zendframework/library/Zend/View/Renderer/PhpRenderer.php(507): include('...')
#14 /vendor/zendframework/zendframework/library/Zend/View/View.php(205): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
#15 /vendor/zendframework/zendframework/library/Zend/Mvc/View/Http/DefaultRenderingStrategy.php(126): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#16 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#17 /vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(472): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#18 /vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent), Array)
#19 /vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(332): Zend\EventManager\EventManager->trigger('render', Object(Zend\Mvc\MvcEvent))
#20 /vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(307): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#21 /public/index.php(16): Zend\Mvc\Application->run()
#22 {main}

**Comment by samirfor** [comment]
@bluebaroncanada Thanks.

**Comment by wuno** [comment]
I am having this problem now. it does not happen on my localhost but it is happening on the live server. Also it does not happen every time. It happens at random and refreshing fixes it.
