### ISSUE TITLE
Session Fixation and ZF2 Session Manager ReadTheDocs Page Question

### ISSUE THREAD

**Issue by HurricaneHarry** [ZF-Commons/ZfcUser#443]
Is ZfcUser Authentication Protected against Session Fixation validation using httpuseragent and/or remoteaddr?

How can I set that level of protection in ZfcUser, or is it completely not in scope of this project?  Why?

Also, when I try to use the suggested 'Zend\Session\SessionManager' as shown here, http://zf2.readthedocs.org/en/latest/modules/zend.session.manager.html

I get kicked out of session. I'm not fully understanding why.

module/Application/Module.php

        $moduleRouteListener->attach($eventManager);
        $this->bootstrapSession($e);

        //** BjyAuthorize Redirection Strategy for site
        $authService = $e->getApplication()->getServiceManager()->get('zfcuser_auth_service');
        $strategy = new RedirectionStrategy();
        
        if(php_sapi_name() == 'cli')
        {
            return;
        }
        
        $req = $e->getApplication()->getServiceManager()->get('Request');
        if(!$authService->hasIdentity())
        {
            //** if not logged in, give the login page a redirect
            $strategy->setRedirectUri(sprintf('http://foo.com/user/login?redirect=%s', $req->getRequestUri()));
        }
        else
        {
            //** if logged in and denied access, place the user on the landing page
            $strategy->setRedirectRoute('zfcuser');
        }

**Comment by adamlundrigan** [comment]
@Danielss89 this can be closed as not an issue relating to ZfcUser.  I'll copy @ojhaujjwal's answer RE: session validators onto a wiki page.
