### ISSUE TITLE
Findall and remove in the user mapper

### ISSUE THREAD

**Issue by stijnhau** [ZF-Commons/ZfcUser#451]
Hello

I think it is a good idea for ZfcUser and ZfcUser doctrine module to have those function added to the core.
These function (especialy findall) are now most of the tyme copies from multiple mapper files to the mapper file they need.
I recommend using those from ZfcUserAdmin module because those look good.
If most of the People think this is a good idea i'll create a PR.

**Comment by stijnhau** [comment]
but is we launch an event then if there need to be other stuff done we can listen to the event.

**Comment by ojhaujjwal** [comment]
@stijnhau Just listening to the event is not enough when people want to implement soft deletion!

Personally, I don't agree with adding the findAll method as well. ZfcUser is meant to be simple by default

**Comment by stijnhau** [comment]
And you can ofcouse always overwrite the remove method. if you want to do custom things.
