### ISSUE TITLE
Set identity that is being logged out on logout event

### ISSUE THREAD

**Issue by roelvanduijnhoven** [ZF-Commons/ZfcUser#466]
The `AdapterChain` emits an `logout` event upon logout. It would be useful for cleanup to know what identity is being logged out.

**Comment by adamlundrigan** [comment]
IMO the best way to accomplish this is to inject the auth service (`zfcuser_auth_service`) into your event listener instance and query it for the user who was logged in.  As a quick test I did this from the `Module::onBootstrap`:

```
$serviceManager = $e->getApplication()->getServiceManager();
$service        = $serviceManager->get('zfcuser_auth_service');
$adapter        = $serviceManager->get('ZfcUser\Authentication\Adapter\AdapterChain');

$adapter->getEventManager()->attach('logout', function($e) use ($service) {
    die(var_dump($service->getIdentity()));
});
```

And I got back the full user entity.

**Comment by roelvanduijnhoven** [comment]
Interesting solution. Seems simpler than my solution. Thanks.

Still would love to see this supported by real API.

**Comment by Danielss89** [comment]
PR accepted ;)
