### ISSUE TITLE
Let users log on using passwords in legacy format

### ISSUE THREAD

**Issue by roelvanduijnhoven** [ZF-Commons/ZfcUser#484]
Users of my old application should still be able to log on into ZfcUser. ZfcUser should have the correct hooks and API to make it possible to configure it this way. 

That is currently not the case. But a combination of #481 and #483 should fix this. Also #482 would be helpful.

**Comment by adamlundrigan** [comment]
@Danielss89 this can be closed as it appears to referenced PRs provide enough of a framework for implementing the requested custom behaviour.
