### ISSUE TITLE
Current Zfcuser sessions saved in Memcached and DB

### ISSUE THREAD

**Issue by teseo** [ZF-Commons/ZfcUser#509]
Hello,

What would be the best practice in order to have the user session in memcached and database?

**Comment by adamlundrigan** [comment]
It's been 6 months, but if you're still wondering take a look at chained storage: http://framework.zend.com/manual/current/en/modules/zend.authentication.intro.html#chain-storage

@Danielss89 this isn't relevant to ZfcUser and so can be closed
