### ISSUE TITLE
ZfcUser destroys all session containers after logout

### ISSUE THREAD

**Issue by asologor** [ZF-Commons/ZfcUser#511]
The problem is that I have ZfcUser module, which stores some data in its own containers in $_SESSION array, and i storing shopping cart items and some other data in separated containers inside $_SESSION. Then I logging out via ZfcUser, and my $_SESSION array becomes totally empty, so my shopping cart becomes empty too.
How can I fix that?

**Comment by intellent** [comment]
Sorry to bring this up again. But how can I restore the old behavior? In my case, I do want to destroy the whole session on logout. I didn’t find a suitable logout event to attach to.
