### ISSUE TITLE
User password regenerate fails to hash passwords.

### ISSUE THREAD

**Issue by erlicthemad** [ZF-Commons/ZfcUser#515]
The function updateUserPasswordHash in Authentication/Adapter/db.php fails to hash a password properly if the old password was hashed with an incorrect hash level. Instead the function stores the password given in cleartext in the password field of the database. This shows if if more than one hash setting is used. I have a bcrypt and md5/bcrypt hash method being used for authentication.

**Comment by adamlundrigan** [comment]
Could you provide some more detail on how you're triggering this bug?  Right now it looks like the only way to avoid that is to update the user's password and call the mapper `update` method to persist it, just as the default credential preprocesor does (https://github.com/ZF-Commons/ZfcUser/blob/1.x/src/ZfcUser/Authentication/Adapter/Db.php#L124)
