### ISSUE TITLE
Security bug: session shared between 2 frameworks in 2 subdomains

### ISSUE THREAD

**Issue by Gamempire** [ZF-Commons/ZfcUser#516]
Hi, I have two ZF2 + ZfcUser different installations in the same server, used by two different subdomain (goofy.mydomain.com, donald.mydomain.com).

In "goofy" I have a user database that is different from the user database of "donald".

When I log in with ZfcUser into "goofy" with a user with id (for example) 12, opening "donald" I automatically result as logged in as the user of the database of "donald" with id 12.

What's happening and how to avoid this?

Thanks

**Comment by adamlundrigan** [comment]
@Danielss89 this can be closed
