### ISSUE TITLE
Arbitrary user name length restriction

### ISSUE THREAD

**Issue by adamlundrigan** [ZF-Commons/ZfcUser#553]
Register form has a length filter which rejects anything < 3 or > 255.  This should be configurable instead of hard-coded.  

https://github.com/ZF-Commons/ZfcUser/blob/master/src/ZfcUser/Form/RegisterFilter.php#L40

**Comment by snapshotpl** [comment]
You can use Delegator Factory, get StringLength and set your own values.

**Comment by Danielss89** [comment]
Hmm i disagree. You can change it in an event, or overwrite the factory.
I wan't to move away from one billion configuration possibilities.

**Comment by adamlundrigan** [comment]
Fair assessment. That was just one suggestion...my main argument is that it's an arbitrary restriction.   Perhaps just eliminate the minimum bound (or set to 1)? If someone needs it they can ‎easily put it back in via an event or delegator factory, as you say.

**Comment by Danielss89** [comment]
Yeah, we could do that. We can remove the min. requirement altogether as the field itself is `required`
