### ISSUE TITLE
login user internally

### ISSUE THREAD

**Issue by mmjamal** [ZF-Commons/ZfcUser#557]
is there a way to login without the form internally when using direct url ? 
and supplying the username and password through the url either by post values or some other way?

**Comment by Danielss89** [comment]
Take a look in the UserController how it logs the user ind. You can do the same, how you get the credentials is up to you.

**Comment by adamlundrigan** [comment]
@mmjamal if you want to by-pass the "frontend" login stuff and just directly inject a specific user into the session container [take a look at my comment here](https://github.com/ZF-Commons/ZfcUser/issues/518#issuecomment-70037011).  That's the approach I use for setting a specific user when in console mode.
