### ISSUE TITLE
Translator: Files in wrong dir

### ISSUE THREAD

**Issue by alexz707** [ZF-Commons/ZfcUser#570]
in 1.2.2 the language folder seems to be in the wrong place.
in Github I see the folder in the root dir but when i download the files via composer it's in /src/ZfcUser/language.

The second thing i discovered is that in 1.2.2. the "Authentication failed. Please try again." message doesn't get translated via the formElementErrors helper because of a change in zf2.
Is there any possibility to fix that in 1.2.2 too? I don't want to upgrade to devmaster in this project becauce it should go productive soon!

Thanks, 
Alex

**Comment by Danielss89** [comment]
This is because you look in the master branch which is 2.x. Please look at the 1.x branch
