### ISSUE TITLE
When login redirect to URL

### ISSUE THREAD

**Issue by guilherme-santos** [ZF-Commons/ZfcUser#574]
Hello,
I make some search and I saw that it's common redirect parameter has the complete url but when log in with redirect parameter in this module, it expect a zf2 route...
I think you should change this line
https://github.com/ZF-Commons/ZfcUser/blob/master/src/ZfcUser/Controller/UserController.php#L183
to use ```toUrl``` instead of ```toRoute```.

What do you think?

**Comment by nepda** [comment]
+1

**Comment by Ocramius** [comment]
This has explicitly been disabled because of security issues, and shouldn't be introduced again.

If you want to use `toUrl()`, simply provide a literal route pointing where you want.

**Comment by guilherme-santos** [comment]
Provide a route don't works for me, because the main reason to use that is, for example... If you are accessing http://localhost/controller/action?query=string and you aren't logged in, after log in you should redirect to the same page you try to access, OR if your session limit expired I don't want the user start all navigation to arrive in the same point that he was!

What kind of security issues you found? Be redirected to another website, for example?

**Comment by Ocramius** [comment]
> What kind of security issues you found? Be redirected to another website, for example?

Standard CSRF and session hijacking attacks: pretty much straight from the manual of how to do them.

**Comment by Danielss89** [comment]
what @Ocramius said + take a look at https://github.com/Eye4web/E4WZfcUserRedirectUrl
