### ISSUE TITLE
Translation property hardcoded

### ISSUE THREAD

**Issue by d-bo** [ZF-Commons/ZfcUser#577]
Hello.
Stuck with translation of
[https://github.com/ZF-Commons/ZfcUser/blob/master/src/ZfcUser/Controller/UserController.php#L52](https://github.com/ZF-Commons/ZfcUser/blob/master/src/ZfcUser/Controller/UserController.php#L52)

I'm interesting, is there a way to override this variable or some kind of quick patch ?

**Comment by stijnhau** [comment]
I think (not 100% sure) that getting the view helper from the service manager and translating inside the controller is the best solution.

    $translate = $this->getServiceLocator()->get('viewhelpermanager')->get('translate');
    $translate('my custom message'));

**Comment by Danielss89** [comment]
see #597
You could just overwrite the view file and check if there's a message in the flash messenger. If there is, then echo your own message instead.
