### ISSUE TITLE
Possible documentation issue for usage of ZfcUser\View\Helper\ZfcUserIdentity

### ISSUE THREAD

**Issue by chrishiebert** [ZF-Commons/ZfcUser#579]
This code snippet from ([check-user-logged-in.md](https://github.com/ZF-Commons/ZfcUser/tree/master/docs/check-user-logged-in.md)) doesn't appear to work since `zfcUserIdentity()` returns `\ZfcUser\Entity\UserInterface` or `false` when invoked.

>The view helper may also return the Authentication Service :
>
>```php
<?php $authService = $this->zfcUserIdentity()->getAuthService(); ?>
```

When added to a view this error is generated when logged out:
```
Fatal error: Call to a member function getAuthService() on a non-object
```
and this error is generated when logged in:
```
Fatal error: Call to undefined method ZfcUser\Entity\User::getAuthService()
```

**Comment by Danielss89** [comment]
Yeah, that's actually wrong. Only the Controller Plugin does that.

**Comment by Danielss89** [comment]
Fixed
