### ISSUE TITLE
Add element to register form but don't save it to db !

### ISSUE THREAD

**Issue by invader7** [ZF-Commons/ZfcUser#582]
Hello , i managed to add some new fields to my form and i want some of them to be saved to the db and some of them to be ignored.

Now i can save all fields but if i delete the unwanted database columns it doesn't work.

I want to validate my form only for some fields and ignore the other , is that possible ? Thanks !

**Comment by Danielss89** [comment]
"Doesn't work" is not a thing. Please always add error messages.

**Comment by invader7** [comment]
It says that database table doesn't have a column with name "the field name that i don't want to save"

I tried with $form->setValidationGroup('only wanted','fields here'); before setData but i had no luck !

**Comment by Danielss89** [comment]
You need to overwrite the ZfcUser entity if you don't want all the fields from the original.
