### ISSUE TITLE
ZfcUser with Twig

### ISSUE THREAD

**Issue by nikolay-kozlov** [ZF-Commons/ZfcUser#583]
Hello!
I'm trying use Twig (ZfcTwig) in template login.phtml
But this code:
<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>
is not work in twig templates.
Can i use Twig with ZfcUser?
Thank you!

**Comment by Danielss89** [comment]
"is not working" is not a very good description. Please explain why it is not working.
