### ISSUE TITLE
Feature: It is Possible to create a ZfcUser from another login type

### ISSUE THREAD

**Issue by SirLouen** [ZF-Commons/ZfcUser#584]
It is Possible to create a ZfcUser from another login type? 
I mean, despite it doesnt have to make sense, if I create a self-made simple login form with email + password could I create a ZfUser object from that info?
I cant see this in the FAQ Wiki :(
Regards

**Comment by Danielss89** [comment]
Yes, of course :) Why shouldn't you be able to do that?

**Comment by SirLouen** [comment]
Could you give me somewhere to look at an example?
Regards

**Comment by Danielss89** [comment]
Look in the ZfcUser controller and services?
