### ISSUE TITLE
Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (ZfcUser ) could not be initialized.

### ISSUE THREAD

**Issue by adarshkhatri** [ZF-Commons/ZfcUser#594]
I know it is duplicate issue which has been already closed.

But I am receiving this error constantly.
I have updated my 'composer.json' with 
"require": {
        "php": ">=5.5",
        "zendframework/zendframework": "~2.5",
        "coolcsn/csn-user": "0.2.0",
        "doctrine/doctrine-orm-module": "^0.9.0",
        "zf-commons/zfc-user": "dev-master"
    }

I also have this in my "application.config.php"
return array(
    // This should be an array of module namespaces used in the application.
    'modules' => array(
        'Application',
        'DoctrineModule',
        'DoctrineORMModule',
        'ZfcBase',
        'ZfcUser '
    ),

Then I have run "composer update" but it didn't help.

Please suggest, I must have missed something.

**Comment by Danielss89** [comment]
What is your error?

**Comment by Danielss89** [comment]
You should not use ZfcUser master! use the newest version under the releases tab.

**Comment by adarshkhatri** [comment]
I just replaced whole folder with version 1.2.2, but same result? Do I need to change anything else?

**Comment by Danielss89** [comment]
Folder? You should use composer so it autoloads correct.

**Comment by adarshkhatri** [comment]
Here is what I did,

go to "vendor" folder in terminal and then run
 "sudo git clone https://github.com/ZF-Commons/ZfcUser.git" (runs successfully)
then run
"sudo composer update" (it updates the composer)

But still having same error, sorry for being too beginner.

**Comment by Danielss89** [comment]
That's not how you use composer.
You should have a composer file for you whole project, not in the vendor.
And if you use composer, you shouldn't use git clone yourself.

Do this: In your main composer, add "zf-commons/zfc-user": "~1.2.2" and then run composer update in your base application folder, where that composer file is. That should automaticly download the zfc-user repo into vendor/zf-commons/zfc-user

**Comment by adarshkhatri** [comment]
Sorry I forgot to mention, I do 
cd -
then only do 
sudo composer update

My composer resides in main root folder of my project.
