### ISSUE TITLE
Issue with ZFCUser Login Widget

### ISSUE THREAD

**Issue by wanfran** [ZF-Commons/ZfcUser#596]
I've been following this solution for introducing a login widget in our site:

https://github.com/ZF-Commons/ZfcUser/wiki/How-to-embed-the-login-form-on-another-page

but pasting the code:

<?php echo $this->zfcUserLoginWidget(); ?>

Returns this error:
ERR_EMPTY_RESPONSE
Both with Chrome and Firefox.

Looking in the apache error log no errors are return

Any ideas of what could be happening

**Comment by Danielss89** [comment]
This doesn't sound like an issue with ZfcUser, if it errors, it should show something in logs.
