### ISSUE TITLE
const ROUTE_LOGIN not configurable

### ISSUE THREAD

**Issue by stijnhau** [ZF-Commons/ZfcUser#598]
I think that the const ROUTE_LOGIN        = 'zfcuser/login'; should be configurable with the moduleOptions.
Any isses when i create a PR for this?

**Comment by Danielss89** [comment]
Why? You can overwrite both the route and the view-script? I think it's good that it "advertises" that it's actually using ZfcUser, makes it easier for the developer.

**Comment by CasperF** [comment]
It's not configurable because it points to the zfcuser controller. Like Daniels said, you can overwrite the route easily. If you really need to change the route login, just extend the zfcuser and put your own route there, although that wouldn't be necessary in the first place I think.

**Comment by stijnhau** [comment]
Oke that it would be implemented.
Created 1 claas that extend zfcUser and when zfcUxer returns a redirect it changes the value of the redirect.
This is needed because based on the url i have multiple layouts so i need to redirect to an other url.
