### ISSUE TITLE
Two ZfcUser on local machine and different ports

### ISSUE THREAD

**Issue by UserGrapo** [ZF-Commons/ZfcUser#599]
Hi,
I have two site on the same local machine both with Zf2 e ZfcUser (the two are 192.168.1.2 and 192.168.1.2:8080).
The problem is that when I log in on one of the two the other become inaccessible as long as I don't log out from the first.
The two site uses different tables for the users.
I know that the problem is from both site using same cookies so I would like to know if I can change some config in ZfcUser to make use of another one for one of the two site.
Hope you can help me, I searched everywhere. Thank you.

**Comment by Danielss89** [comment]
ZfcUser does not use cookies, well it off course use a session cookie, but you should have separate installs, so the sessions doesn't clash.

**Comment by UserGrapo** [comment]
The two installation are separate, the problem is that both use "PHPSESSID" cookie that is only one because both site are on the same domain 192.168.1.2.
There's any way to make two zf2 e ZfcUser work on same ip on different port without session clash?

**Comment by adamlundrigan** [comment]
You'll need to update your applications to use different session names or storage paths.  

 - [Session Config - ZF2 Manual](http://framework.zend.com/manual/current/en/modules/zend.session.config.html)
 - [AkrabatSession module](https://github.com/akrabat/AkrabatSession)

**Comment by UserGrapo** [comment]
Thanks, that solved my problem.
