### ISSUE TITLE
This project needs changelog

### ISSUE THREAD

**Issue by svycka** [ZF-Commons/ZfcUser#601]
This module is used by many people also has many addons so I think its time to add changelog. Every time new version released I have to go thought commits to see what changed, most of the time it's not important changes but sometimes even not BC breaking changes can be important.

Or maybe that just me who can't find where it is :)

**Comment by Danielss89** [comment]
Usually the changes should be described in the release message(look under releases tab).
I do a agree though, we should have a changelog.
