### ISSUE TITLE
CRUD over users database

### ISSUE THREAD

**Issue by cbichis** [ZF-Commons/ZfcUser#602]
Hi,

I have a project where the user is not registering himself. Rather a staff person is adding (registering) from backend the user.

As far as I checked ZFCUser may not be so appropriate for this case just by a simple reason that after registering the user the redirect is not made to login page but rather to a users list page. Which is different than ROUTE_LOGIN used for users (normal users, staff) to login...

If I am correct it may worth to consider adding this case to ZfcUser...

**Comment by stijnhau** [comment]
Check fot the zfcUserAdmin module.

**Comment by cbichis** [comment]
I wasnt looking for a full backend system for users (usually the backend is more complex than just user management hence using ZfcUserAdmin is not suitable)...

More for a way to use ZfcUser for to allow handle crud over users database within a third party ZF based backend system...

**Comment by stijnhau** [comment]
so what is the problem with zfcAdmin.
Oke that there are other admin options needed for your proram but those should be other modules.

**Comment by cbichis** [comment]
Using ZfcAdmin is forcing to use not just for user backend but for the whole app backend... Thats not what I was looking for :)

**Comment by Danielss89** [comment]
I'm not quite sure what it is you are asking? Can you please explain what it is you are missing?

**Comment by stijnhau** [comment]
i propose closing this because no response.
