### ISSUE TITLE
Login works on localhost but in 1&1 failed - session_regenerate_id

### ISSUE THREAD

**Issue by Paul75** [ZF-Commons/ZfcUser#603]
Hello,

In localhost it works but in the 1&1 hebergement it failed.

I have this error :
Warning: session_regenerate_id(): Cannot regenerate session id - headers already sent in /homepages/11/d588599106/htdocs/hall/vendor/zendframework/zend-session/src/SessionManager.php on line 301

Any help ?

Thanks

**Comment by Danielss89** [comment]
what is "1&1 hebergement"?
It sounds like you output some data to the browser before instantiating Zend Framework?
When you output something, headers will be sent, hence the "headers already sent..." message

**Comment by Paul75** [comment]
1&1 is "hosting".
In localhost it works fine ....

Not in the real server : I'm using 1&1 (http://www.1and1.fr/)

Thanks

**Comment by Danielss89** [comment]
Maybe the hosting provider (1&1) is outputting something for you. Sorry, this is not something we really can help with, as it is not an issue with the module, but rather your own setup.
