### ISSUE TITLE
Get module name in layout.phtml

### ISSUE THREAD

**Issue by tasmaniski** [ZF-Commons/ZfcUser#605]
I am trying to get module name in layout.phtml but I am getting an empty value.
Is there any way to get that info?

```
$this->getHelperPluginManager()->getServiceLocator()
    ->get('application')->getMvcEvent()->getRouteMatch()->getParams();
 ```

I got only controller and action:
```
  'controller' => 'zfcuser'
  'action' => 'login'
```

**Comment by Danielss89** [comment]
This is not a ZfcUser question. Try asking in #zftalk on IRC.
