### ISSUE TITLE
Password cost change sets password field value to plain text at next login

### ISSUE THREAD

**Issue by rbroen** [ZF-Commons/ZfcUser#611]
When registring, the password is stored as a hash ($2y$10$PpTw...), say with cost 10. All is well.
After changing the cost value to 11, the first login is successful, but zfcuser notices the hash has cost 10 and updates the user entity... with a plain password in the database.
The next time a user logs in, log in will fail. 

Is this a known issue?

**Comment by Rockstar04** [comment]
https://github.com/ZF-Commons/ZfcUser/blob/1.x/src/ZfcUser/Authentication/Adapter/Db.php#L118-L127

This looks like the issue with the code here. Line 124 should handle hashing the password....

What exact version of ZFCUser are you seeing this with? This is potentially a very big issue from a data security standpoint, aside from the fact that the user can no longer log in.

**Comment by rbroen** [comment]
I just tested this and will add some more info; the version is 2.0.x-dev, composer tells me I'm up to date.

To reproduce:
1. create a zf2 project with zfcuser and add some users.
2. set a breakpoint on the ZfcUser\Authentication\Adapter\Db on line 107  
      $this->updateUserPasswordHash($userObject, $credential, $cryptoService);
3. look at the user record in the database (like with phpmyadmin)
4. change the password_cost in your config/autoload/zfcuser.global.php (just increase by a few)
5. go to the login page and log in as the user.
6. when the breakpoint is reached, verify the database field for the password (still looks like $2$10$Ppm...)
7. step into updateUserPasswordHash() to line 131, take a look at $user (plain password here).
8. right after the update() on line 131, the password is written as plain text in the database.

The user has been successfully logged in, but will not be able to next time.

**Comment by Danielss89** [comment]
Don't use version 2.x(master), it is not ready at all!
Use the 1.x branch. And look at the releases tab.
