### ISSUE TITLE
Registration form (errors)

### ISSUE THREAD

**Issue by Goldfinch** [ZF-Commons/ZfcUser#613]
After add this https://github.com/ZF-Commons/ZfcUser/issues/612#issuecomment-165948349
we don't see any errors, but errors from form after validation we don't get
I think here need some fix to:

1. in service https://github.com/ZF-Commons/ZfcUser/blob/1.x/src/ZfcUser/Service/User.php#L74

change
```php
        $form->setData($data);
        if (!$form->isValid()) {
            return false;
        }
```
to
```php
        $form->setData($data);
        if (!$form->isValid()) {
            return $form;
        }
```

2. in controller https://github.com/ZF-Commons/ZfcUser/blob/1.x/src/ZfcUser/Controller/UserController.php#L218

change
```php
        if (!$user) {
            return array(
                'registerForm' => $form,
                'enableRegistration' => $this->getOptions()->getEnableRegistration(),
                'redirect' => $redirect,
            );
        }
```
to
```php
        if (is_callable(array($user, 'isValid')) && !$user->isValid()) {
            return array(
                'registerForm' => $user,
                'enableRegistration' => $this->getOptions()->getEnableRegistration(),
                'redirect' => $redirect,
            );
        }
```
result

![Image](http://clip2net.com/clip/m456895/85a24-clip-21kb.png?nocache=1)

**Comment by Danielss89** [comment]
Thanks. Should be fixed in newly released version 1.4.2.
https://github.com/ZF-Commons/ZfcUser/releases/tag/1.4.2
