### ISSUE TITLE
partial in view

### ISSUE THREAD

**Issue by Goldfinch** [ZF-Commons/ZfcUser#614]
https://github.com/ZF-Commons/ZfcUser/blob/1.x/view/zfc-user/user/changeemail.phtml#L16
https://github.com/ZF-Commons/ZfcUser/blob/1.x/view/zfc-user/user/changepassword.phtml#L20
https://github.com/ZF-Commons/ZfcUser/blob/1.x/view/zfc-user/user/login.phtml#L11
https://github.com/ZF-Commons/ZfcUser/blob/1.x/view/zfc-user/user/register.phtml#L15

in each template skipped argument $form

![Image](http://clip2net.com/clip/m456895/cdb84-clip-26kb.png?nocache=1)

I think need to fix in each template

```php
<?php echo $this->partial('_form.phtml', array('form' => $form)); ?>
```

**Comment by Danielss89** [comment]
Thanks. Should be fixed in newly released version 1.4.2.
https://github.com/ZF-Commons/ZfcUser/releases/tag/1.4.2
