### ISSUE TITLE
service_manager - form errors

### ISSUE THREAD

**Issue by N3XT0R** [ZF-Commons/ZfcUser#615]
Hello Guys,

please fix your last modification in config or in the relevant classes.
Since the last update the service manager can't load the form classes in, at example:
https://github.com/ZF-Commons/ZfcUser/blob/1.x/src/ZfcUser/Service/User.php#L207 

because the form factory class is not registered in the service_manager config.

**Comment by Danielss89** [comment]
Thanks. Should be fixed in newly released version 1.4.2.
https://github.com/ZF-Commons/ZfcUser/releases/tag/1.4.2
