### ISSUE TITLE
Custom fields on table users

### ISSUE THREAD

**Issue by tsens** [ZF-Commons/ZfcUser#616]
I Want use ZfcUser but i can't change the structure fields for my custom user table...
have a solution for this?

**Comment by Danielss89** [comment]
You can create your own user entity and specify it in the config file.

**Comment by tsens** [comment]
Yes, but about the different fields in this table: 
ds_email instead email
nm_usuario instead username

**Comment by Danielss89** [comment]
Ok, you have to write your own mapper.
