### ISSUE TITLE
ServiceManagerAwareInterface

### ISSUE THREAD

**Issue by dymen1** [ZF-Commons/ZfcUser#623]
**Deprecated: ServiceManagerAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceManagerAwareInitializer. Please update your class ZfcUser\Authentication\Storage\Db to remove the implementation, and start injecting your dependencies via factory instead.**

I am using zf-commons/zfc-user (1.4.2) and I get this with ZF version is 2.5.3.

Are there any plans to support the servicemanager 2.7.5 release?

**Comment by Danielss89** [comment]
@dymen1 I have not looked into the 2.7.5 release. Do you know what is needed to support that version?

**Comment by dymen1** [comment]
@Danielss89 All **ServiceLocatorAwareInterface**and **ServiceManagerAwareInterface** implementations need to be removed and replaced by factory injection, I am currently aliasing these factories so zfcUser uses these to generate it's classes.
- 'ZfcUser\Authentication\Adapter\Db'
- 'ZfcUser\Authentication\Storage\Db'
- 'zfcuser_user_service'
But there is currently another issue running within the ZF mvc package https://github.com/zendframework/zend-mvc/issues/87

**Comment by svycka** [comment]
If you not going to refactor soon maybe add zendframework/zend-mvc <2.7 to composer and release new version? this is really annoying

**Comment by Danielss89** [comment]
I'm going to do the refactor this weekend.

**Comment by Danielss89** [comment]
Also: PR welcome if you really need it ASAP!

**Comment by valexkeepcalm** [comment]
Hi all! So, how best to solve this problem?

**Comment by ZeinEddin** [comment]
Will this be fixed soon? Is [#627](https://github.com/ZF-Commons/ZfcUser/pull/627) ok to be used?

**Comment by dymen1** [comment]
@ZeinEddin it isn't official and doesn't support BC.

**Comment by MelleDijkstra** [comment]
Also getting this issue, hope that it's fixed soon

**Comment by stijnhau** [comment]
Have did a test for the master branch
https://github.com/stijnhau/ZfcUser/commit/e331c828647d9b41e997f63b55e55e685787b4b9
Not a fan of the servicemanerg object everwhere i think it's best toi inject all the dependencies.
Are you agreeing witrh me before i do all the refactoring?

**Comment by svycka** [comment]
@stijnhau I think this is better, but does it solve deprecated *AwareInterface problem?

**Comment by stijnhau** [comment]
It does.
Altough still need to do this on a lot more classes.
So it's a WIP.

**Comment by Danielss89** [comment]
Fix in #637

**Comment by hongkongpfui** [comment]
Can we reopen this as ZfcUser\Service\User still use this interface?

**Comment by Danielss89** [comment]
@hongkongpfui Fixed in 1.4.4

**Comment by miqueiasrafael** [comment]
On my return only:
-------------------------------
A value for the identity was not provided prior to authentication with ObjectRepository authentication adapter

in GIT

https://gist.github.com/miqueiasrafael/b8fb93873442e527dea9e1def351acf8
