### ISSUE TITLE
Creating user doesn't work on zfcUser 3.0

### ISSUE THREAD

**Issue by stijnhau** [ZF-Commons/ZfcUser#668]
Statement could not be executed (HY000 - 1364 - Field 'user_id' doesn't have a default value)

**Comment by riceri** [comment]
Hi, in the ZF3 version of ZfcUser they have change the name of user_id to id. So update your user table and it will work.

**Comment by stijnhau** [comment]
They haven't.
At least i still see refference to user8id in the code like in the databse scheme

**Comment by riceri** [comment]
Sorry, what version did i upgrade to that forced that change then...

**Comment by stijnhau** [comment]
the dev-master ;)

**Comment by riceri** [comment]
Just noticed that it was you who did that commits :)

**Comment by stijnhau** [comment]
Yes buit thats opther branch and has n,othing to do wioth this.
Restarted server and is working now so closed.
