### ISSUE TITLE
Captcha for login form

### ISSUE THREAD

**Issue by lampi87** [ZF-Commons/ZfcUser#679]
Hello,

is it possible to add captcha to login form?
If yes, how?
Or is it possible to replace used login form by configuration?

Thank you,
Alex!

**Comment by ZeinEddin** [comment]
You can use captcha, have a look in the documentation:
[https://github.com/ZF-Commons/ZfcUser/wiki/How-to-use-image-captcha](https://github.com/ZF-Commons/ZfcUser/wiki/How-to-use-image-captcha)

**Comment by lampi87** [comment]
Thank you for the link.
Unfortunately it just seems to work for registration form.
My request/question is related to LOGIN form.

**Comment by lampi87** [comment]
I've created a pull request #680 as it was not possible
